CREATE TABLE "stg_stammdaten_mq" (
  "mq_id15" bigint NOT NULL,
  "mq_kurzname" varchar NOT NULL,
  "strasse" varchar,
  "position" varchar,
  "pos_detail" varchar,
  "richtung" varchar,
  "lon_wgs84" numeric(10,6),
  "lat_wgs84" numeric(10,6),
  "snapshot_date" date,
  "source_file" varchar,
  "ingested_at" timestamptz
);

CREATE TABLE "stg_stammdaten_detector" (
  "det_id15" bigint NOT NULL,
  "mq_id15" bigint NOT NULL,
  "det_name_alt" varchar,
  "det_name_neu" varchar,
  "spur" varchar,
  "annotation" varchar,
  "kommentar" varchar,
  "inbetriebnahme" date,
  "abbaudatum" date,
  "deinstalliert" varchar,
  "lon_wgs84" numeric(10,6),
  "lat_wgs84" numeric(10,6),
  "snapshot_date" date,
  "source_file" varchar,
  "ingested_at" timestamptz
);

CREATE TABLE "stg_old_det_val_hr" (
  "detid_15" bigint NOT NULL,
  "tag" date NOT NULL,
  "stunde" int NOT NULL,
  "qualitaet" decimal(5,2),
  "q_kfz_det_hr" int,
  "v_kfz_det_hr" int,
  "q_pkw_det_hr" int,
  "v_pkw_det_hr" int,
  "q_lkw_det_hr" int,
  "v_lkw_det_hr" int,
  "source_file" varchar,
  "ingested_at" timestamptz
);

CREATE TABLE "stg_old_mq_hr" (
  "mq_name" varchar NOT NULL,
  "tag" date NOT NULL,
  "stunde" int NOT NULL,
  "qualitaet" decimal(5,2),
  "q_kfz_mq_hr" int,
  "v_kfz_mq_hr" int,
  "q_pkw_mq_hr" int,
  "v_pkw_mq_hr" int,
  "q_lkw_mq_hr" int,
  "v_lkw_mq_hr" int,
  "source_file" varchar,
  "ingested_at" timestamptz
);

CREATE TABLE "stg_new_detector_hourly" (
  "det_name_alt" varchar NOT NULL,
  "det_index" int NOT NULL,
  "datum_ortszeit" date NOT NULL,
  "stunde_ortszeit" int NOT NULL,
  "vollstaendigkeit" numeric(12,6),
  "zscore_det0" numeric(12,6),
  "zscore_det1" numeric(12,6),
  "zscore_det2" numeric(12,6),
  "hist_cor" numeric(12,6),
  "local_time" timestamptz,
  "month" int,
  "qkfz" int,
  "qlkw" int,
  "qpkw" int,
  "utc" timestamptz,
  "vkfz" int,
  "vlkw" int,
  "vpkw" int,
  "source_file" varchar,
  "ingested_at" timestamptz
);

CREATE TABLE "dim_mq" (
  "mq_id15" bigint PRIMARY KEY,
  "mq_kurzname" varchar UNIQUE NOT NULL,
  "strasse" varchar,
  "position" varchar,
  "pos_detail" varchar,
  "richtung" varchar,
  "lon_wgs84" numeric(10,6),
  "lat_wgs84" numeric(10,6)
);

CREATE TABLE "dim_detector" (
  "det_id15" bigint PRIMARY KEY,
  "mq_id15" bigint NOT NULL,
  "det_name_alt" varchar UNIQUE,
  "det_name_neu" varchar,
  "spur" varchar,
  "annotation" varchar,
  "kommentar" varchar,
  "inbetriebnahme" date,
  "abbaudatum" date,
  "deinstalliert" varchar,
  "lon_wgs84" numeric(10,6),
  "lat_wgs84" numeric(10,6)
);

CREATE TABLE "dim_vehicle_class" (
  "vehicle_class_id" smallint PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "label" varchar
);

CREATE TABLE "dim_time_hour" (
  "ts_utc" timestamptz PRIMARY KEY,
  "date_local" date,
  "hour_local" int,
  "month_local" int
);

CREATE TABLE "fact_detector_hourly" (
  "det_id15" bigint NOT NULL,
  "ts_utc" timestamptz NOT NULL,
  "vehicle_class_id" smallint NOT NULL,
  "flow_q" int,
  "speed_v" int,
  "source_layout" varchar NOT NULL,
  "created_at" timestamptz
);

CREATE TABLE "fact_mq_hourly" (
  "mq_id15" bigint NOT NULL,
  "ts_utc" timestamptz NOT NULL,
  "vehicle_class_id" smallint NOT NULL,
  "flow_q" int,
  "speed_v" int,
  "source_layout" varchar NOT NULL,
  "created_at" timestamptz
);

CREATE TABLE "fact_quality_hourly" (
  "det_id15" bigint NOT NULL,
  "ts_utc" timestamptz NOT NULL,
  "quality_old" numeric(12,6),
  "completeness_new" numeric(12,6),
  "zscore_det0" numeric(12,6),
  "zscore_det1" numeric(12,6),
  "zscore_det2" numeric(12,6),
  "hist_cor" numeric(12,6),
  "source_layout" varchar NOT NULL,
  "created_at" timestamptz
);

CREATE TABLE "pipeline_run" (
  "run_id" uuid PRIMARY KEY,
  "started_at" timestamptz NOT NULL,
  "finished_at" timestamptz,
  "status" varchar NOT NULL,
  "source_year" int,
  "source_month" int,
  "source_layout" varchar,
  "notes" varchar
);

CREATE TABLE "qa_features_hourly" (
  "det_id15" bigint NOT NULL,
  "ts_utc" timestamptz NOT NULL,
  "run_id" uuid NOT NULL,
  "row_count" int,
  "missing_rate" numeric(18,6),
  "duplicate_rate" numeric(18,6),
  "freshness_lag_h" int
);

CREATE TABLE "ml_anomaly_score_hourly" (
  "det_id15" bigint NOT NULL,
  "ts_utc" timestamptz NOT NULL,
  "run_id" uuid NOT NULL,
  "model_name" varchar NOT NULL,
  "anomaly_score" numeric(12,6) NOT NULL,
  "is_anomaly" boolean,
  "top_driver" varchar,
  "driver_value" numeric(12,6)
);

CREATE TABLE "kpi_definition" (
  "kpi_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kpi_name" varchar UNIQUE NOT NULL,
  "description" text,
  "grain" varchar NOT NULL,
  "owner" varchar,
  "formula" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "version" int NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "kpi_value" (
  "kpi_id" int NOT NULL,
  "ts_utc" timestamptz NOT NULL,
  "entity_type" varchar NOT NULL,
  "entity_id" bigint,
  "value" numeric(18,6),
  "run_id" uuid NOT NULL,
  "calculated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "kpi_confidence" (
  "kpi_id" int NOT NULL,
  "ts_utc" timestamptz NOT NULL,
  "entity_type" varchar NOT NULL,
  "entity_id" bigint,
  "confidence_score" numeric(12,6),
  "confidence_label" varchar,
  "freshness_score" numeric(12,6),
  "volume_score" numeric(12,6),
  "null_score" numeric(12,6),
  "anomaly_score" numeric(12,6),
  "drift_score" numeric(12,6),
  "run_id" uuid NOT NULL,
  "calculated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX ON "stg_stammdaten_mq" ("mq_id15", "snapshot_date");

CREATE INDEX ON "stg_stammdaten_mq" ("mq_kurzname");

CREATE UNIQUE INDEX ON "stg_stammdaten_detector" ("det_id15", "snapshot_date");

CREATE INDEX ON "stg_stammdaten_detector" ("mq_id15");

CREATE INDEX ON "stg_stammdaten_detector" ("det_name_alt");

CREATE UNIQUE INDEX ON "stg_old_det_val_hr" ("detid_15", "tag", "stunde");

CREATE INDEX ON "stg_old_det_val_hr" ("tag");

CREATE UNIQUE INDEX ON "stg_old_mq_hr" ("mq_name", "tag", "stunde");

CREATE INDEX ON "stg_old_mq_hr" ("tag");

CREATE UNIQUE INDEX ON "stg_new_detector_hourly" ("det_name_alt", "det_index", "utc");

CREATE INDEX ON "stg_new_detector_hourly" ("datum_ortszeit");

CREATE INDEX ON "stg_new_detector_hourly" ("utc");

CREATE INDEX ON "dim_mq" ("mq_kurzname");

CREATE INDEX ON "dim_detector" ("mq_id15");

CREATE INDEX ON "dim_detector" ("det_name_alt");

CREATE UNIQUE INDEX ON "fact_detector_hourly" ("det_id15", "ts_utc", "vehicle_class_id");

CREATE INDEX ON "fact_detector_hourly" ("ts_utc");

CREATE INDEX ON "fact_detector_hourly" ("det_id15");

CREATE UNIQUE INDEX ON "fact_mq_hourly" ("mq_id15", "ts_utc", "vehicle_class_id");

CREATE INDEX ON "fact_mq_hourly" ("ts_utc");

CREATE INDEX ON "fact_mq_hourly" ("mq_id15");

CREATE UNIQUE INDEX ON "fact_quality_hourly" ("det_id15", "ts_utc");

CREATE INDEX ON "fact_quality_hourly" ("ts_utc");

CREATE INDEX ON "fact_quality_hourly" ("det_id15");

CREATE UNIQUE INDEX ON "qa_features_hourly" ("det_id15", "ts_utc", "run_id");

CREATE INDEX ON "qa_features_hourly" ("run_id");

CREATE UNIQUE INDEX ON "ml_anomaly_score_hourly" ("det_id15", "ts_utc", "run_id", "model_name");

CREATE INDEX ON "ml_anomaly_score_hourly" ("run_id");

CREATE INDEX ON "kpi_definition" ("grain");

CREATE INDEX ON "kpi_definition" ("is_active");

CREATE UNIQUE INDEX ON "kpi_value" ("kpi_id", "ts_utc", "entity_type", "entity_id");

CREATE INDEX ON "kpi_value" ("run_id");

CREATE INDEX ON "kpi_value" ("entity_type", "entity_id");

CREATE UNIQUE INDEX ON "kpi_confidence" ("kpi_id", "ts_utc", "entity_type", "entity_id");

CREATE INDEX ON "kpi_confidence" ("run_id");

CREATE INDEX ON "kpi_confidence" ("entity_type", "entity_id");


-- =========================================================
-- Added: Ingestion + Raw Landing (manifest + raw rows)
-- =========================================================

CREATE TABLE "ingestion_runs" (
  "run_id" uuid PRIMARY KEY,
  "triggered_by" varchar NOT NULL,
  "status" varchar NOT NULL,
  "started_at" timestamptz NOT NULL,
  "ended_at" timestamptz,
  "notes" text,
  "payload" jsonb
);

CREATE TABLE "ingestion_file_manifest" (
  "source_url" text PRIMARY KEY,
  "dataset_version" varchar NOT NULL,
  "source_type" varchar NOT NULL,
  "month_key" varchar NOT NULL,

  "checksum_sha256" varchar NOT NULL,
  "bytes" bigint,
  "last_modified" timestamptz,

  "first_seen_at" timestamptz NOT NULL,
  "last_seen_at" timestamptz NOT NULL,

  "last_ingested_at" timestamptz,
  "last_ingestion_run_id" uuid,
  "last_status" varchar NOT NULL,
  "metadata" jsonb
);

CREATE TABLE "ingestion_run_files" (
  "run_id" uuid NOT NULL,
  "source_url" text NOT NULL,
  "action" varchar NOT NULL,
  "row_count" bigint,
  "message" text,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("run_id", "source_url")
);

CREATE TABLE "raw_traffic_rows" (
  "id" bigint PRIMARY KEY,
  "run_id" uuid NOT NULL,
  "source_url" text NOT NULL,
  "month_key" varchar NOT NULL,
  "dataset_version" varchar NOT NULL,
  "source_type" varchar NOT NULL,
  "row_number" bigint NOT NULL,
  "payload" jsonb NOT NULL,
  "loaded_at" timestamptz NOT NULL
);

ALTER TABLE "dim_detector" ADD FOREIGN KEY ("mq_id15") REFERENCES "dim_mq" ("mq_id15");

ALTER TABLE "fact_detector_hourly" ADD FOREIGN KEY ("det_id15") REFERENCES "dim_detector" ("det_id15");

ALTER TABLE "fact_detector_hourly" ADD FOREIGN KEY ("ts_utc") REFERENCES "dim_time_hour" ("ts_utc");

ALTER TABLE "fact_detector_hourly" ADD FOREIGN KEY ("vehicle_class_id") REFERENCES "dim_vehicle_class" ("vehicle_class_id");

ALTER TABLE "fact_mq_hourly" ADD FOREIGN KEY ("mq_id15") REFERENCES "dim_mq" ("mq_id15");

ALTER TABLE "fact_mq_hourly" ADD FOREIGN KEY ("ts_utc") REFERENCES "dim_time_hour" ("ts_utc");

ALTER TABLE "fact_mq_hourly" ADD FOREIGN KEY ("vehicle_class_id") REFERENCES "dim_vehicle_class" ("vehicle_class_id");

ALTER TABLE "fact_quality_hourly" ADD FOREIGN KEY ("det_id15") REFERENCES "dim_detector" ("det_id15");

ALTER TABLE "fact_quality_hourly" ADD FOREIGN KEY ("ts_utc") REFERENCES "dim_time_hour" ("ts_utc");

ALTER TABLE "qa_features_hourly" ADD FOREIGN KEY ("det_id15") REFERENCES "dim_detector" ("det_id15");

ALTER TABLE "qa_features_hourly" ADD FOREIGN KEY ("ts_utc") REFERENCES "dim_time_hour" ("ts_utc");

ALTER TABLE "qa_features_hourly" ADD FOREIGN KEY ("run_id") REFERENCES "pipeline_run" ("run_id");

ALTER TABLE "ml_anomaly_score_hourly" ADD FOREIGN KEY ("det_id15") REFERENCES "dim_detector" ("det_id15");

ALTER TABLE "ml_anomaly_score_hourly" ADD FOREIGN KEY ("ts_utc") REFERENCES "dim_time_hour" ("ts_utc");

ALTER TABLE "ml_anomaly_score_hourly" ADD FOREIGN KEY ("run_id") REFERENCES "pipeline_run" ("run_id");

ALTER TABLE "kpi_value" ADD FOREIGN KEY ("kpi_id") REFERENCES "kpi_definition" ("kpi_id");

ALTER TABLE "kpi_value" ADD FOREIGN KEY ("ts_utc") REFERENCES "dim_time_hour" ("ts_utc");

ALTER TABLE "kpi_value" ADD FOREIGN KEY ("run_id") REFERENCES "pipeline_run" ("run_id");

ALTER TABLE "kpi_confidence" ADD FOREIGN KEY ("kpi_id") REFERENCES "kpi_definition" ("kpi_id");

ALTER TABLE "kpi_confidence" ADD FOREIGN KEY ("ts_utc") REFERENCES "dim_time_hour" ("ts_utc");

ALTER TABLE "kpi_confidence" ADD FOREIGN KEY ("run_id") REFERENCES "pipeline_run" ("run_id");

-- Ingestion/RAW relations
ALTER TABLE "ingestion_run_files" ADD FOREIGN KEY ("run_id") REFERENCES "ingestion_runs" ("run_id");
ALTER TABLE "ingestion_run_files" ADD FOREIGN KEY ("source_url") REFERENCES "ingestion_file_manifest" ("source_url");
ALTER TABLE "raw_traffic_rows" ADD FOREIGN KEY ("run_id") REFERENCES "ingestion_runs" ("run_id");
ALTER TABLE "raw_traffic_rows" ADD FOREIGN KEY ("source_url") REFERENCES "ingestion_file_manifest" ("source_url");

